name: pilipala
description: A new Flutter project.
publish_to: "none"

version: 1.0.25+1025

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # 图标与取色（保持与 Flutter 3.24.x 兼容，具体版本由下方 overrides 固定）
  cupertino_icons: ^1.0.5
  dynamic_color: ^1.7.0

  get: ^4.6.5

  # 网络
  dio: ^5.4.1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  connectivity_plus: ^6.0.3
  dio_http2_adapter: ^2.3.1+1

  # 图片
  cached_network_image: ^3.3.0
  saver_gallery: ^3.0.1

  # 存储
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # 设备信息
  device_info_plus: ^9.0.0
  # 权限
  permission_handler: ^11.3.0
  # 分享
  share_plus: ^7.0.2
  # cookie 管理
  webview_cookie_manager: ^2.0.6
  # 浏览器
  webview_flutter: ^4.8.0
  # 解决sliver滑动不同步
  extended_nested_scroll_view: ^6.2.1
  # 上拉加载
  loading_more_list: ^6.0.0
  # 下拉刷新
  pull_to_refresh_notification: ^3.0.1
  # 图标
  font_awesome_flutter: ^10.4.0
  # toast
  flutter_smart_dialog: ^4.9.4
  # 下滑关闭
  dismissible_page: ^1.0.2
  custom_sliding_segmented_control: ^1.8.3
  # 加密
  crypto: ^3.0.3
  encrypt: ^5.0.3

  # 视频播放器（使用稳定版，避免 SDK 36 强制要求）
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4

  # 媒体通知
  audio_service: ^0.18.13
  audio_session: ^0.1.18

  # 音量、亮度、屏幕控制
  flutter_volume_controller: ^1.3.2
  screen_brightness: ^0.2.2+1
  wakelock_plus: ^1.1.6
  universal_platform: ^1.1.0
  # 进度条
  audio_video_progress_bar: ^2.0.3
  auto_orientation: ^2.3.1
  protobuf: ^3.0.0

  # 获取app信息
  package_info_plus: ^4.2.0
  url_launcher: ^6.2.6
  flutter_svg: ^2.0.10+1
  # 防抖节流
  easy_debounce: ^2.0.3
  # 高帧率
  flutter_displaymode: ^0.6.0
  # scheme跳转
  appscheme: ^1.0.8
  # 弹幕
  ns_danmaku:
    git:
      url: https://github.com/guozhigq/flutter_ns_danmaku.git
      ref: master
  # 状态栏图标控制
  status_bar_control: ^3.2.1
  # 代理
  system_proxy: ^0.1.0
  # pip
  floating:
    git:
      url: https://github.com/guozhigq/floating.git
      ref: main
  # html解析
  html: ^0.15.4
  # html渲染
  flutter_html: ^3.0.0-beta.2
  # 极验
  gt3_flutter_plugin: ^0.1.0
  uuid: ^3.0.7
  scrollable_positioned_list: ^0.3.8
  catcher_2: ^1.2.6
  logger: ^2.3.0
  path: ^1.9.0
  # 电池优化
  disable_battery_optimization: ^1.1.1
  # 展开/收起
  expandable: ^5.0.1
  # 投屏
  dlna_dart: ^0.0.8
  lottie: ^3.1.2
  # 二维码
  qr_flutter: ^4.1.0
  bottom_sheet: ^4.0.4
  web_socket_channel: ^2.4.5
  brotli: ^0.6.0
  # 文本语法高亮
  re_highlight: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.8

# 仅做兼容性“降级”覆盖，避免 Flutter 3.24.x 缺失新 Color API 导致编译错误
dependency_overrides:
  dynamic_color: 1.6.9
  font_awesome_flutter: 10.7.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo/logo_android_2.png
  image_path_android: assets/images/logo/logo_android_2.png
  image_path_ios: assets/images/logo/logo_ios.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/images/logo/logo_android_2.png
  adaptive_icon_monochrome: assets/images/logo/logo_android_2.png
  macos:
    generate: true
    image_path: assets/images/logo/logo_ios.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/lv/
    - assets/images/logo/
    - assets/images/live/
    - assets/images/video/
  fonts:
    - family: fansCard
      fonts:
        - asset: assets/fonts/fansCard.ttf
    - family: Jura-Bold
      fonts:
        - asset: assets/fonts/Jura-Bold.ttf