name: Build APK (arm64-v8a only)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'

      # 关键：同时安装平台 36 和新 aapt2（build-tools 34）
      - name: Prepare Android SDK (platform 36 + build-tools 34.0.0)
        shell: bash
        run: |
          SDKMANAGER="${ANDROID_SDK_ROOT:-$ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager"
          yes | "${SDKMANAGER}" --licenses || true
          yes | "${SDKMANAGER}" "platforms;android-36" "build-tools;34.0.0" || true

      - name: Get dependencies
        run: flutter pub get

      - name: Generate keystore (like original project)
        run: |
          keytool -genkey -v -keystore android/app/vvex.jks \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass temp123456 -keypass temp123456 \
            -alias tempkey \
            -dname "CN=Temp, OU=Temp, O=Temp, L=Temp, S=Temp, C=US"

      - name: Build APK (arm64-v8a only)
        run: flutter build apk --release --target-platform android-arm64
        env:
          KEYSTORE_PASSWORD: temp123456
          KEY_ALIAS: tempkey
          KEY_PASSWORD: temp123456

      - name: Get version
        id: version
        run: |
          VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: //' | sed 's/+.*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: |
          mkdir -p output
          cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
             output/pilipala-v${{ steps.version.outputs.version }}-arm64-v8a.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pilipala-arm64-v8a
          path: output/*.apk
          if-no-files-found: error