name: Build APK (arm64-v8a only, preflight auto-setup)

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Preflight Android SDK (install platform 34 + build-tools 34.0.0)
        shell: bash
        run: |
          set +e
          
          ANDROID_SDK_ROOT=${ANDROID_SDK_ROOT:-/usr/local/lib/android/sdk}
          SDKMANAGER="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          
          ( yes 2>/dev/null || true ) | "$SDKMANAGER" --licenses >/dev/null 2>&1
          
          "$SDKMANAGER" --install \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "platform-tools" >/dev/null 2>&1
          
          set -e
          
          echo "=== Installed Android platforms ==="
          ls -la "$ANDROID_SDK_ROOT/platforms/" 2>/dev/null || echo "(none)"
          echo ""
          echo "=== Installed build-tools ==="
          ls -la "$ANDROID_SDK_ROOT/build-tools/" 2>/dev/null || echo "(none)"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: stable
          cache: true

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate keystore (if missing)
        run: |
          if [ ! -f android/app/vvex.jks ]; then
            keytool -genkey -v -keystore android/app/vvex.jks \
              -keyalg RSA -keysize 2048 -validity 10000 \
              -storepass temp123456 -keypass temp123456 \
              -alias tempkey \
              -dname "CN=Temp, OU=Temp, O=Temp, L=Temp, S=Temp, C=US"
          fi

      - name: Build APK (arm64-v8a only)
        run: flutter build apk --release --target-platform android-arm64
        env:
          KEYSTORE_PASSWORD: temp123456
          KEY_ALIAS: tempkey
          KEY_PASSWORD: temp123456

      - name: Get version
        id: version
        run: |
          VERSION=$(grep "^version:" pubspec.yaml | sed 's/version: //' | sed 's/+.*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Rename APK
        run: |
          mkdir -p output
          cp build/app/outputs/flutter-apk/app-release.apk \
             output/pilipala-v${{ steps.version.outputs.version }}-arm64-v8a.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pilipala-arm64-v8a
          path: output/*.apk
          if-no-files-found: error